server {
    server_name support.innexo.solutions suporte.innexo.solutions;

    location / {
        proxy_pass         http://127.0.0.1:3080;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
        proxy_hide_header  Cache-Control;
        add_header         Cache-Control "no-store, must-revalidate" always;
    }

    listen 443 ssl;
    ssl_certificate     /etc/letsencrypt/live/innexo.solutions/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/innexo.solutions/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = support.innexo.solutions) { return 301 https://$host$request_uri; }
    if ($host = suporte.innexo.solutions) { return 301 https://$host$request_uri; }
    listen 80;
    server_name support.innexo.solutions suporte.innexo.solutions;
    return 404;
}
